Repository kheeyaa/Who-ate-my-fish, pull requests merged in 2021-11, with the labels that each got.

#6 chore: Add image files
  src/assets/images/cats/cat1.svg
  src/assets/images/cats/cat1_jail.svg
  src/assets/images/cats/cat2.svg
  src/assets/images/cats/cat2_jail.svg
  src/assets/images/cats/cat3.svg
  src/assets/images/cats/cat3_jail.svg
  src/assets/images/cats/cat4.svg
  src/assets/images/cats/cat4_jail.svg
  src/assets/images/cats/cat5.svg
  src/assets/images/cats/cat5_jail.svg
  src/assets/images/cats/cat6.svg
  src/assets/images/cats/cat6_jail.svg
  src/assets/images/cats/jail.svg
  src/assets/images/fish.png
  src/assets/images/fish.svg
  src/assets/images/message.png
  src/assets/images/message.svg
  src/assets/images/message_exit.png
  src/assets/images/message_exit.svg
  src/assets/images/message_new.png
  src/assets/images/message_new.svg
  src/assets/images/moon.png
  src/assets/images/moon.svg
  src/assets/images/sprite_main.png
  src/assets/images/sun.png
  src/assets/images/sun.svg
Labels: documentation, priority: low, status: done

#10 "feat: info-header styling done"
  src/index.html
  src/sass/layout/_info.scss
Labels: style, priority: medium

#12 Add styles to game-status section.
  src/index.html
  src/sass/layout/_info.scss
  src/sass/utils/_index.scss
  src/sass/utils/_media-query.scss
Labels: style, priority: medium, status: pending

#14 feat: edit info.scss
  src/index.html
  src/sass/layout/_info.scss
Labels: style, priority: medium

#17 feat: Add socket event to modify user info & current users' image
  package-lock.json
  server.js
  src/index.html
  src/js/app.js
  src/sass/layout/_info.scss
Labels: priority: medium, status: pending

#27 feat: make gameInfo object for setting mafia and citizens
  server.js
Labels: enhancement, priority: medium, status: pending

#28 feat: setting mafia and citizen secretCode UI
  server.js
  src/js/app.js
Labels: enhancement, status: to do, priority: medium

#30 feat: create modal for gameover
  public/images/cats/civilwin.png
  public/images/cats/mafiawin.png
  server.js
  src/index.html
  src/sass/layout/_main.scss
Labels: documentation, enhancement, style, priority: medium, status: done

#31 feat: Add socket event to send vote result to server
  server.js
  src/js/app.js
  src/sass/layout/_info.scss
Labels: enhancement, priority: medium, status: pending

#32 Implement changeInfoImage, changeInfoColorMode functions
  src/db/secretCode.json
  src/index.html
  src/js/app.js
  src/sass/layout/_info.scss
  src/sass/utils/_color.scss
Labels: enhancement, style, priority: medium, status: done

#33 Implement function that changes info game status
  server.js
  src/index.html
  src/js/app.js
Labels: enhancement, priority: medium, status: pending

#34 refactor: server.js refactoring and get secret code from database
  db/secretCode.json
  server.js
  src/js/app.js
Labels: enhancement, priority: medium, status: pending

#35 feat: toggle button & timer function
  src/js/app.js
  src/sass/layout/_info.scss
Labels: enhancement, priority: medium, status: pending

#37 feat: architect client state structure
  src/js/app.js
Labels: refactor, rename, status: pending

#40 feat: game result logic done
  server.js
  src/index.html
  src/js/app.js
  src/sass/layout/_main.scss
Labels: enhancement, priority: medium, status: pending

#41 feat: add function of sendVoteResult
  server.js
  src/js/app.js
Labels: enhancement, priority: medium, status: pending

#43 feat: Modify sendVoteResult function to send socket event differently…
  public/sound/bubble-sound.m4a
  public/sound/mouse-click.mp3
  src/js/app.js
Labels: enhancement, priority: medium, status: pending

#45 Implement vote status function
  server.js
  src/js/app.js
Labels: enhancement, priority: medium, status: pending

#46 feat: add music button
  public/images/play.png
  public/images/stop.png
  server.js
  src/assets/images/play.png
  src/assets/images/stop.png
  src/index.html
  src/js/app.js
  src/js/chat/events.js
  src/js/chat/functions.js
  src/js/chat/state.js
  src/js/game/events.js
  src/js/game/functions.js
  src/js/game/state.js
  src/js/socket.js
  src/sass/layout/_main.scss
Labels: documentation, enhancement, style, priority: medium, status: pending

#47 feat: add control selection button function & gameInfo property
  server.js
  src/index.html
  src/js/app.js
Labels: enhancement, priority: medium, status: pending

#48 Implement night vote status function
  server.js
Labels: enhancement, priority: medium, status: pending

#49 feat: get civil user number & fix selection control button
  server.js
  src/js/app.js
Labels: bug, enhancement, status: pending

#51 Fix minor bug
  server.js
Labels: bug, priority: high, status: pending

#52 feat: server refactor and add feature
  server.js
  src/index.html
  src/js/app.js
  src/sass/layout/_info.scss
  src/sass/layout/_main.scss
Labels: documentation, refactor, priority: medium

#53 feat: disconnect feature when game over
  server.js
  src/js/app.js
Labels: bug, priority: high, status: done

#54 feat: Add deactive screen on chat & vote container
  src/index.html
  src/js/app.js
  src/sass/layout/_full-chat.scss
  src/sass/layout/_info.scss
  src/sass/layout/_main.scss
Labels: style, priority: low, status: done

#55 feat: Add toggle function to app.js
  src/js/app.js
Labels: style, priority: medium, status: pending

#56 feat: Implement day/night toggle function
  server.js
Labels: bug, enhancement, priority: high, status: pending

#57 fix: Debug night change event
  server.js
Labels: bug, priority: high, status: pending

#58 Develop
  server.js
  src/index.html
  src/js/app.js
Labels: bug, priority: medium, status: pending

#60 feat: server files refactoring and img change when civil win
  public/images/cats/civilwin.png
  server.js
  src/index.html
  src/js/app.js
Labels: refactor, priority: medium

#61 feat: Implement korean last consonant function
  src/js/app.js
Labels: enhancement, priority: medium, status: done

#62 feat: server files refactoring and connect with frontend
  server.js
  src/js/app.js
Labels: refactor, priority: high, status: done

#63 refactor: Modify variable names
  src/js/app.js
Labels: refactor, rename, status: pending

#64 fix: error when 5+ people enter
  server.js
  src/js/app.js
Labels: bug, priority: high, status: pending

#67 fix: fix error when 5+ people enter
  server.js
  src/js/app.js
Labels: bug, enhancement, priority: medium
